import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is autogenerated from the folder structure under `docs/`.
//
// You do not normally edit this file: drop Markdown files into `docs/`, control
// their order with `sidebar_position` front matter, and group them into sections
// with subfolders + a `_category_.json` in each. Autoscribe follows the same
// convention when it writes pages, so the nav stays in sync automatically.
//
// See https://docusaurus.io/docs/sidebar for the full reference.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
